[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 original_bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
BOT_TOKEN = "8059528086:AAFIZLlNJzo_nUplHlXzjyShla-DsT0RNYw"
API_ID = "29784596"
API_HASH = "4f330d47c4fa2a9732caa0036942c5a9"
BOT_USERNAME = "Facemedobookbot"
ADMIN_ID = "5509130673"